### ISSUE TITLE
Positions reset when exiting and reopening

### ISSUE THREAD

**Issue by jdrusso** [Nitwel/Immersive-Home#85]
Seems like the positions of placed entities reset upon closing and opening. The relative positions are correct, but it seems like the reference is skewed. 

Additionally, I can see the "Edit room" boundary balls have moved. Again, their relative positions are correct, but the whole configuration has moved. 

Not sure if it's related to redrawing boundaries? Is there anything I should be doing to make sure persistence works correctly?

**Comment by Nitwel** [comment]
What headset are you using? I've noticed that sometimes when fiddling with boundaries, the position of the origin moves thus breaking the configured room and all placed entities.

I'll soon implement a way to recalibrate your room if this situation occurs so that hopefully should solve that problem to some extend.

**Comment by jdrusso** [comment]
It's a Quest 3 -- that sounds like exactly what I'm seeing

Sounds like you're on it! One possible recalibration procedure could be a simple rotation of the origin with one of the thumb sticks, using the drawn room boundaries as a visual guide. Maybe there's something more sophisticated/automated. 

(Super cool repo btw!)
